### PR TITLE
Support all bcrypt versions

### PR DESCRIPTION
**Pull request by kingkorf**
- [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

### Changes proposed in this pull request:

 - Support all bcrypt versions, see https://en.wikipedia.org/wiki/Bcrypt#Versioning_history

/cc @nats-io/core

### CODE REVIEW

**Comment by kingkorf** [comment]
Travis build fail is not because of my code..

**Comment by derekcollison** [comment]
I figured it would be. We could speed it up by just looking for `$` at first character before invoking the regex.

**Comment by kingkorf** [comment]
I was first thinking along these lines but this just doesn't feel right. Maybe worth a quick bench comparison anyway.

```
// Support for bcrypt stored passwords and tokens.
const bcryptPrefixA = "$2a$"
const bcryptPrefixX = "$2x$"
const bcryptPrefixY = "$2y$"
const bcryptPrefixB = "$2b$"

// isBcrypt checks whether the given password or token is bcrypted.
func isBcrypt(password string) bool {
	return strings.HasPrefix(password, bcryptPrefixA) || strings.HasPrefix(password, bcryptPrefixX) || strings.HasPrefix(password, bcryptPrefixY) || strings.HasPrefix(password, bcryptPrefixB)
}
```

**Comment by derekcollison** [comment]
I would just look at first char directly and if a `$` do regex.

**Comment by kingkorf** [comment]
See #1429

**Pull request merged**
