### PR TITLE
Use monotonic time for measuring time internally

### PR DESCRIPTION
**Pull request by wallyqs**
- [x] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

### CODE REVIEW

**Review by derekcollison — COMMENTED** [review]
I think it was @ripienaar who wanted all times in UTC?

If this is internal only I think we are good, but want to make sure if we surface any of these externally they are UTC.

**Comment by ripienaar** [comment]
Yes APIs responding in UTC is best. This light even be considered a breaking change?

**Comment by wallyqs** [comment]
All these should not be front facing, they are used for the internal timers link ping interval etc... which if you call UTC then switch to being in wall clock mode so prone to clock skews.

**Comment by ripienaar** [comment]
Ah all right then it’s fine. Sorry was just going off Derek’s comment (on my phone, code review hard)

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
