### PR TITLE
Fix for #3682 (Take 2): do not delay PINGs for GATEWAY or spoke LEAF connections

### PR DESCRIPTION
**Pull request by sandykellagher**
This change is required to ensure failover of leaf node connections

This contribution is my original work and I license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

/cc @nats-io/core

### CODE REVIEW

**Comment by derekcollison** [comment]
ok will take a look in a bit. Thanks.

**Comment by sandykellagher** [comment]
First simple change was not correct, because sendPing flag would never get set for spokeLeafNode connections.
So I have tidied up the logic and inverted the test for gateway or spokeLeafNode to be a positive test (reads easier!)

**Comment by sandykellagher** [comment]
Hi,
We have run into a similar issue with an intra-cluster connection, when testing system robustness by disconnecting or powering down one of the servers in our standard 3-cluster server.

The issue is that it takes a long time (several minutes) before the other servers in the cluster detect the loss of server A. And the logs show that this happens as a result of a WriteDeadline failure rather than through ping-pong detection mechanism.

In the time between physical network disconnection and the loss being detected, any request messages published to a queue group subscription may get forwarded to the dead server - which of course cannot respond.

So I think in client line 4558, the test for always sending a ping should include c.Kind == ROUTER as well as c.Kind == GATEWAY. 

TBH my personal preference would be to update c.last only for received traffic, but IIRC making that change triggered a Travis test failure. Or perhaps the condition for holding off a ping is limited to receiving a ping from the other side within the specified interval (rather than general traffic)

Does that make sense?  As it stands, it seems that intra-cluster ROUTER connections remain in a zombie state for quite a long time when the network connection is pulled, where I would expect them to be closed by the ping-pong monitoring mechanism.

**Comment by sandykellagher** [comment]
Thinking some more, I'd suggest that we don't need to check the type of connection (c.Kind).

I think the rule should be "send a ping if we've not received any message traffic or a ping from the other end within the specified ping interval, or an RTT measurement is required". And this applies for all connection types.

If we update cp.ping.last for receive traffic as well as pings, then a single test on cp.ping.last is all we need.

**Pull request merged**
