### PR TITLE
[FIXED] New staticcheck fixes

### PR DESCRIPTION
**Pull request by derekcollison**
@neilalexander I do believe this uncovered two off by one conditions in node48 under stree. Could you take a look, kept that change separate.

### CODE REVIEW

**Review by neilalexander — APPROVED** [review]
Confirmed the fix with an update to the node48 unit test.

**Review by derekcollison — COMMENTED** [review]
LGTM - Thanks.

**Comment by derekcollison** [comment]
@neilalexander would need official LGTM from you or @wallyqs

**Review by neilalexander — APPROVED** [review]
LGTM

**Pull request merged**
