### PR TITLE
Add descriptions to JetStream streams and consumers.

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ripienaar** [comment]
LGTM but should we at the same time add them to the consumers for sources and mirrors?

**Comment by derekcollison** [comment]
You mean auto-add them to any direct consumer we place on a mirror or consumer? What name should we use?

**Comment by ripienaar** [comment]
Yes, when I see a mirror or source not working I also tend to see 1000s of failed API requests. Then I use nats event or just a sub to see what is going on. So in my original WIP PR I added descriptions to the consumer create requests indicating what stream is making those requests

**Comment by derekcollison** [comment]
Let's sync up next week and we can do a separate PR. Want to understand a bit better.

**Pull request merged**
