### PR TITLE
Mappings breaking changes

### PR DESCRIPTION
**Pull request by ripienaar**
This undoes some breaking changes made in https://github.com/nats-io/nats-server/pull/3814

/cc @nats-io/core

### CODE REVIEW

**Comment by ripienaar** [comment]
These are in use by `nats server mappings`

**Comment by ripienaar** [comment]
Not sure if I dont have the right permissions for Travis but I cant seem to rebuild just the failing job, if one of you have it please kick that job there are some flappers.

I've kicked a full rebuild twice and each time different fails so maybe more luck rebuilding just the one failing one

**Comment by neilalexander** [comment]
> Not sure if I dont have the right permissions for Travis but I cant seem to rebuild just the failing job, if one of you have it please kick that job there are some flappers.
> 
> I've kicked a full rebuild twice and each time different fails so maybe more luck rebuilding just the one failing one

Will kick the failing job.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
