### PR TITLE
[FIXED] Slow ack for snapshots could cause slow consumer and client disconnect.

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
Thanks @wallyqs, I want to make sure @ripienaar has a chance to double check the cli and the headers such that they do not affect anything. They shouldn't since we normally check len(m.Data) == 0 but want him to confirm.

**Review by ripienaar — APPROVED** [review]
LGTM, did some tests to add awareness of this to cli and nice to get the error.  But non breaking change for older CLI, so all good!

**Review by neilalexander — APPROVED** [review]
LGTM

**Pull request merged**
