### PR TITLE
Limit branch builds to main and dev

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by Jarema — APPROVED** [review]
LGTM!

**Review by neilalexander — APPROVED** [review]

**Review by derekcollison — COMMENTED** [review]
What happens when an external person submits PR, will this not do a build for those?

**Comment by bruth** [comment]
External PRs will kick off an PR-based build ([example](https://github.com/nats-io/nats-server/pull/4297)), but not a branch build by default. So this should not affect that behavior.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
