### PR TITLE
[FIXED] Consumer NumPending incorrect on certain stream setups.

### PR DESCRIPTION
**Pull request by derekcollison**
When a consumer was created that filtered out partial sets of messages with deliver last by subject, and this was on a stream that had max message per subject set and > 1 and the matching filtered messages did have some subjects > 1 the num pending was incorrect.

This could happen with KV streams and history > 1 with duplicates and could result in not getting the initial data set done signal for a watcher.

Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

**Comment by aricart** [comment]
I did a quick test, and it looks like tombstones are not getting reported, so DEL on a watch are missing.

**Comment by aricart** [comment]
The test I have simply creates a KV, adds 4 values, then deletes some - when I ask for the keys, deleted keys are missing.

**Comment by derekcollison** [comment]
Travis was not working so was a bit in flight. I just did a force push, try that one.

**Review by kozlovic — APPROVED** [review]
LGTM. Ran tests locally and they pass.. but check with Alberto's test that seem to be reported a change in behavior.

**Comment by derekcollison** [comment]
I think he got caught in between fixes, @aricart can you re-run yours now?

**Comment by aricart** [comment]
@derekcollison seems to work!

**Comment by aricart** [comment]
@derekcollison all JavaScript tests pass.

**Pull request merged**
