### PR TITLE
[FIXED] Make sure when SubjectState is called we have loaded fss state.

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

**Review by kozlovic — COMMENTED** [review]
I have checked "all" references of mb.fss to see if there were other cases where we did not make sure that the per-subject info was loaded. The only place I found is writeMsgRecord() where we say that if `mb.fss != nil` then we track per-subject info. Does that mean that if the state was flushed then we would no longer keep track of new messages?

**Review by kozlovic — APPROVED** [review]
I was altering the new test to see if I could make it fail but I couldn't. I did increase the block size to 32K and yes, I can verify that in that case after expiration the writeMsgRecord does not track the subject, however since we ensure that we rebuild when checking for mb.fss then it should be ok. I would like confirmation that we are ok in that situation (expiration and then write that are not tracked) before LGTM it.

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
we don't need fss load to write a new msg, we will update psim but fss not needed.

**Pull request merged**
