### PR TITLE
[FIXED] Service across accounts and leaf nodes

### PR DESCRIPTION
**Pull request by matthiashanel**
Tests #1336

Signed-off-by: Matthias Hanel <mh@synadia.com>

### CODE REVIEW

**Comment by derekcollison** [comment]
So if we just designate B as a hub this works..

**Comment by derekcollison** [comment]
I have located the conditional where we bail and do not send the interest. Like I said if we make B act as a hub (which IMO it is in this case) works fine as is.

**Comment by matthiashanel** [comment]
> I have located the conditional where we bail and do not send the interest. Like I said if we make B act as a hub (which IMO it is in this case) works fine as is.

Are you saying the direction in which the route is created matters to getting a response?

**Comment by derekcollison** [comment]
ok I do think this case should still work without the hub designation for B and found a fix. Will update this PR.

**Comment by derekcollison** [comment]
It can, that role is important to some interest propagation but in this case I believe it still should have worked as is and found why it was not. Its fixed.

**Pull request merged**
