### PR TITLE
Remote auth

### PR DESCRIPTION
**Pull request by wenzheng**
This PR is to add the functionality to support the remote authentication and authorization instead of pure local configuration way for users and their permissions.

Detailed information will be included in the README file

### CODE REVIEW

**Comment by petemiron** [comment]
@wenzheng We've specified requirements and proposed a reference code framework in issue #434. Can you review and see if you can map your current design to those requirements and give us additional feedback on it? One of the areas that I think are particularly important to keep an eye on is performance implications, while maintaining the security of the solution.

**Comment by firebook** [comment]
@petemiron 
1.  I thing we should be able to inject arguments for the plugin in the configuration. For example, when I check the remote auth, I can get information like remote auth endpoint, proxy setting .etc from config file. 
2. We also should add strategy for auth. For example, I have three user, one is local configured user, one is jwt auth user, one is remote auth user, when client connect, I can decide which plugin should be first one to validate it, or I can decide which plugin is the only one to validate it.

**Comment by derekcollison** [comment]
We have a design for the new nkey functionality that will also eventually include some form of remote access to additional information for auth. You can do customAuth now if you want, otherwise hold tight for just awhile longer. Thanks for the patience.

**Comment by VladimirAkopyan** [comment]
"You can do customAuth now " - sorry, could you explain? I couldn't find anything related to it.

**Comment by antmanler** [comment]
@VladimirAkopyan  gnatsd is supported as embedded server in your code, just like streaming server do, then you can pass your customAuth to [`Options.CustomClientAuthentication`](https://github.com/nats-io/gnatsd/blob/master/server/opts.go#L96)

here is a example to support jwt auth using customAuth
https://github.com/antmanler/gnatsd-jwt

**Comment by derekcollison** [comment]
Yes and @VladimirAkopyan we will be adding our own JWT using nkeys with accounts and account isolation soon. Adding straight nkeys now which will remove any need for NATS servers to have a user's private key.

**Comment by derekcollison** [comment]
I am closing this since we are about to release 2.0 with nkeys and signed JWT support.

**Pull request closed without merging**
