### PR TITLE
[FIXED] JetStream: possible lock inversion

### PR DESCRIPTION
**Pull request by kozlovic**
When updating usage, there is a lock inversion in that the jetStream
lock was acquired while under the stream's (mset) lock, which is
not correct. Also, updateUsage was locking the jsAccount lock, which
again, is not really correct since jsAccount contains streams, so
it should be jsAccount->stream, not the other way around.

Removed the locking of jetStream to check for clustered state since
js.clustered is immutable.

Replaced using jsAccount lock to update usage with a dedicated lock.

Originally moved all the update/limit fields in jsAccount to new
structure to make sure that I would see all code that is updating
or reading those fields, and also all functions so that I could
make sure that I use the new lock when calling these. Once that
works was done, and to reduce code changes, I put the fields back
into jsAccount (although I grouped them under the new usageMu mutex
field).

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by matthiashanel — APPROVED** [review]
LGTM, Mind putting that lock into lockordering.txt?

**Comment by kozlovic** [comment]
@matthiashanel Will update the file, but keep in mind that this lock is "independent", meaning that any other lock can get it, since no code under `updateMu` lock grabs another one (well, maybe expect ipQueue to push, but ipQueue lock again is independent, used only to add/dequeue to/from ipQueue list).

**Comment by matthiashanel** [comment]
ok.

**Review by matthiashanel — APPROVED** [review]
LGTM

**Pull request merged**
