### PR TITLE
publish an advisory when jetstream is enabled for an account

### PR DESCRIPTION
**Pull request by ripienaar**
Not urgent at all

### CODE REVIEW

**Comment by ripienaar** [comment]
If you are accessing a service it’s good to know what comes and goes as features in your account. It’s important to be able to figure out what version is running - I want to add version to account info too but that won’t tell us anything about a cluster state 

So personally I would find this easy as an event for a JS admin to keep track of. Even in a large cluster since you might want to confirm uniform versions are in use in all the fleet you are connected to

Obviously they are published just at start so you might miss them - but they can go into a stream as they are published late.

**Comment by derekcollison** [comment]
First you can't depend on version, think more blackbox operations. And we have a pull API to query whether its enabled which feels correct for account managers. This event does not seem to do much, since the way it is every server is sending these even on a server restart which is bad imo. Also not sure if you did it but would need a disable version too and hope they don't miss one. I think I prefer a query mode here.

**Comment by ripienaar** [comment]
The version matters a lot even in black box operations. There could be a particular version one wish to avoid or a minimum requirement for a new feature to be present. 

I think for sure account operators will want to see version info and I agree an advisory isn’t the best way but I don’t see them as inherently bad as you do - but that’s fine we can close this, I think we need another way to expose version info and how that will look probably depends on how clustering shakes out

**Comment by derekcollison** [comment]
Point is version info can change based on what server you are connected to. Even if for just a rolling update. So what does the person looking at the version do?

**Comment by ripienaar** [comment]
The opposite question is more important. 

There will be bugs like the one we recently fixed that is serious enough that it can impact data integrity. People will and do care what version they run against. 

We need to find a way for them to be able to answer that question. Is this the best way to expose that? Nope. 

Advisories isn’t queries true but as someone observing casually or via a event monitor having a stream of servers starting with some additional data about those servers is valuable to send to event viewers. Advisories are not guaranteed delivery that’s true for any advisory. 

A query interface would be needed too

**Comment by derekcollison** [comment]
Servers already introduce themselves on startup and every 30 seconds with version info.

**Comment by ripienaar** [comment]
Only to system accounts so not going to be available to some rando JS enabled account

**Comment by derekcollison** [comment]
Yes valid point but I was working with Matthias on ways to expose those so we can coordinate with those efforts. That work?

**Comment by ripienaar** [comment]
Yes could work for the advisory case, We would have to see I think some query interface would be important 

Like perhaps account info could return an array of unique versions in the cluster serving the account. Rather than expose it on a per server basis? 

What I am looking at isn’t if this particular thing is the right way or can be not picked about - but how can we design a way to answer that question and I think there’s a combo of advisories + query responses that helps people get to the info they need

**Comment by derekcollison** [comment]
Agree.

**Pull request closed without merging**
