### PR TITLE
fix js nex interest check where leaf node masked gw subj propagation

### PR DESCRIPTION
**Pull request by matthiashanel**
basically a gw subject propagation issue could be hidden behind a leaf
node.
also change error text when this was the case

Signed-off-by: Matthias Hanel <mh@synadia.com>

### CODE REVIEW

**Review by kozlovic — COMMENTED** [review]
Looks good. Working on adding a test that demonstrates the issue without this fix. Will add to the PR, so let's not merge now.

**Comment by kozlovic** [comment]
@matthiashanel I have added the test in commit: https://github.com/nats-io/nats-server/pull/3016/commits/bcb0baa410a68886baec857334f801ce4970db7a. It failed consistently on main branch and passed (at least locally) on your branch. Will see if it fails or not on Travis.

**Comment by matthiashanel** [comment]
@kozlovic the test looks good to me

**Review by kozlovic — APPROVED** [review]
LGTM

**Pull request merged**
