### PR TITLE
changing NEXT expires field from time to duration in nanoseconds

### PR DESCRIPTION
**Pull request by matthiashanel**
Signed-off-by: Matthias Hanel <mh@synadia.com>

Moved this into a separate branch as per @wallyqs suggestion.

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ripienaar** [comment]
LGTM

**Comment by scottf** [comment]
This change made me verify the java client for fields that send/receive a duration. In summary of this change and based on the api at https://github.com/nats-io/jetstream this is what the java client now sends and expects. Does this match the server?

Stream Configuration / Info
```
max_age: microseconds (nano / 1000)
duplicate_window: microseconds  (nano / 1000)
```

Consumer Configuration
```
ack_wait: nanoseconds
```
	
Next Message Pull or +NXT body 
```
CONSUMER.MSG.NEXT expires: nanoseconds
```

**Comment by wallyqs** [comment]
I see that time.Duration is used for all fields in the StreamConfig struct, so believe all of them are in nanoseconds...

```go
type StreamConfig struct { 
	// ...
	MaxAge       time.Duration   `json:"max_age"`
	Duplicates   time.Duration   `json:"duplicate_window,omitempty"`
	// ...
}
```

https://github.com/nats-io/nats-server/blob/1068529575e768cd5dc6238215117bf65f29794f/server/stream.go#L40-L58

**Comment by scottf** [comment]
> I see that time.Duration is used for all fields in the StreamConfig and ConsumerConfig struct, so believe all of them are in nanoseconds...
> 
> ```go
> type StreamConfig struct { 
> 	// ...
> 	MaxAge       time.Duration   `json:"max_age"`
> 	Duplicates   time.Duration   `json:"duplicate_window,omitempty"`
> 	// ...
> }
> ```
> 
> https://github.com/nats-io/nats-server/blob/1068529575e768cd5dc6238215117bf65f29794f/server/stream.go#L40-L58
> 
> https://github.com/nats-io/nats-server/blob/504652a16f17b8f871ca80da4de266a04ecd9aa6/server/consumer.go#L55

**Comment by scottf** [comment]
Sorry I closed / reopened, I just meant to comment. But I am glad I brought the nano/micro issue up, is it as simple as the api doc needs to be updated?

**Comment by ripienaar** [comment]
Updating it now

**Comment by matthiashanel** [comment]
@ripienaar @wallyqs @scottf @ColinSullivan1 This branch passes locally and in cicd. Unless there's an objection I'll merge this branch in an hour but not before all travis builds have passed.

**Pull request merged**
