### PR TITLE
Add automaxprocs package

### PR DESCRIPTION
**Pull request by 1995parham**
### Changes proposed in this pull request:

 - Add [`automaxprocs`](https://pkg.go.dev/go.uber.org/automaxprocs) package
 - By using this, package `gomaxprocs` will respect the CPU quota on containers environment

As an example, the Kubernetes bare metal has 24 cores but our container has only 4 cores and NATS gomaxprocs is set to 24 which cause many go threads. You can check the performance results [here](https://github.com/uber-go/automaxprocs#performance)

/cc @nats-io/core

### CODE REVIEW

**Comment by derekcollison** [comment]
This looks good to me, looping in a few others. Thanks for the contribution!

**Review by kozlovic — CHANGES_REQUESTED** [review]
I did a `go mod tidy` that did update the go.mod/sum files, please do so and update the PR. One of the deps in the go.sum file has a license that is not the typical MIT, etc.. so not sure what that means for this PR.

**Comment by 1995parham** [comment]
@kozlovic I have done it.

**Comment by derekcollison** [comment]
Thanks!

**Comment by kozlovic** [comment]
@derekcollison I am ok to merge this PR, but we are getting the following race quite often now in several PRs. Not sure if it shows up due to use of Go 1.18 or some recent code change:
```
=== RUN   TestJetStreamClusterPeerExclusionTag
==================
WARNING: DATA RACE
Read at 0x00c001748600 by goroutine 91:
  runtime.mapaccess2_faststr()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/runtime/map_faststr.go:108 +0x0
  github.com/nats-io/nats-server/v2/server.(*Server).updateRouteSubscriptionMap()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/route.go:1549 +0x4d0
  github.com/nats-io/nats-server/v2/server.(*client).processUnsub()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2880 +0x7f3
  github.com/nats-io/nats-server/v2/server.(*raft).unsubscribe()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1496 +0x330
  github.com/nats-io/nats-server/v2/server.(*raft).shutdown()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1417 +0x2d3
  github.com/nats-io/nats-server/v2/server.(*raft).Stop()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1395 +0x30
  github.com/nats-io/nats-server/v2/server.(*Server).shutdownRaftNodes()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:591 +0x310
  github.com/nats-io/nats-server/v2/server.(*Server).Shutdown()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1862 +0x53
  github.com/nats-io/nats-server/v2/server.(*cluster).shutdown()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/test_test.go:267 +0xc5
  github.com/nats-io/nats-server/v2/server.TestJetStreamClusterPeerExclusionTag.func3()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster_test.go:3614 +0x39
  runtime.deferreturn()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/runtime/panic.go:436 +0x32
  testing.tRunner()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1486 +0x47
Previous write at 0x00c001748600 by goroutine 185:
  runtime.mapassign_faststr()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/nats-io/nats-server/v2/server.(*Server).updateRouteSubscriptionMap()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/route.go:1562 +0x5e8
  github.com/nats-io/nats-server/v2/server.(*client).processSubEx()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2517 +0xaca
  github.com/nats-io/nats-server/v2/server.(*client).processSub()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2409 +0x430
  github.com/nats-io/nats-server/v2/server.(*Server).systemSubscribe()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/events.go:1902 +0x37c
  github.com/nats-io/nats-server/v2/server.(*stream).setStreamAssignment()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:567 +0x444
  github.com/nats-io/nats-server/v2/server.(*Account).addStreamWithAssignment()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:491 +0x1a89
  github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2781 +0x735
  github.com/nats-io/nats-server/v2/server.(*jetStream).processStreamAssignment()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2523 +0xaf9
  github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterUpdateStream()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2681 +0x7d6
  github.com/nats-io/nats-server/v2/server.(*jetStream).processUpdateStreamAssignment()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2616 +0x82f
  github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaEntries()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:1506 +0x893
  github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:925 +0xbf0
  github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster-fm()
      <autogenerated>:1 +0x39
Goroutine 91 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1486 +0x724
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1839 +0x99
  testing.tRunner()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1439 +0x213
  testing.runTests()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1837 +0x7e4
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.18.3.linux.amd64/src/testing/testing.go:1719 +0xa71
  github.com/nats-io/nats-server/v2/server.TestMain()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/sublist_test.go:1454 +0x292
  main.main()
      _testmain.go:3187 +0x317
Goroutine 185 (running) created at:
  github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:3016 +0x84
  github.com/nats-io/nats-server/v2/server.(*jetStream).setupMetaGroup()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:626 +0x104f
  github.com/nats-io/nats-server/v2/server.(*Server).enableJetStreamClustering()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:519 +0x20a
  github.com/nats-io/nats-server/v2/server.(*Server).enableJetStream()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:402 +0x1188
  github.com/nats-io/nats-server/v2/server.(*Server).EnableJetStream()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:208 +0x651
  github.com/nats-io/nats-server/v2/server.(*Server).Start()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1749 +0x1797
  github.com/nats-io/nats-server/v2/server.RunServer.func1()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/server_test.go:90 +0x39
==================
    testing.go:1312: race detected during execution of test
--- FAIL: TestJetStreamClusterPeerExclusionTag (1.77s)
```

**Pull request merged**
