### PR TITLE
Common store test for `LoadNextMsgMulti`

### PR DESCRIPTION
**Pull request by neilalexander**
It concerns me a little that by duplicating the same test for both file and memory stores, that differences could slip in later that mean we are no longer testing for consistency between the two stores.

This approach allows us to write tests that only use the `StreamStore` API and have them tested against all store permutations.

Signed-off-by: Neil Twigg <neil@nats.io>

### CODE REVIEW

**Comment by neilalexander** [comment]
Example:
```
=== RUN   TestStoreMsgLoadNextMsgMulti
=== RUN   TestStoreMsgLoadNextMsgMulti/Memory
=== RUN   TestStoreMsgLoadNextMsgMulti/File
=== RUN   TestStoreMsgLoadNextMsgMulti/File/None-None
=== RUN   TestStoreMsgLoadNextMsgMulti/File/None-S2
=== RUN   TestStoreMsgLoadNextMsgMulti/File/AES-GCM-None
=== RUN   TestStoreMsgLoadNextMsgMulti/File/AES-GCM-S2
=== RUN   TestStoreMsgLoadNextMsgMulti/File/ChaCha20-Poly1305-None
=== RUN   TestStoreMsgLoadNextMsgMulti/File/ChaCha20-Poly1305-S2
--- PASS: TestStoreMsgLoadNextMsgMulti (0.65s)
    --- PASS: TestStoreMsgLoadNextMsgMulti/Memory (0.00s)
    --- PASS: TestStoreMsgLoadNextMsgMulti/File (0.65s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/None-None (0.11s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/None-S2 (0.11s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/AES-GCM-None (0.11s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/AES-GCM-S2 (0.11s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/ChaCha20-Poly1305-None (0.11s)
        --- PASS: TestStoreMsgLoadNextMsgMulti/File/ChaCha20-Poly1305-S2 (0.11s)
PASS
ok      github.com/nats-io/nats-server/v2/server
```

**Review by derekcollison — COMMENTED** [review]
I am generally in favor.

A couple of points though.

1. For tests that really have nothing to do with all permutations this seems quite wasteful and we do have some of those tests.
2. Make sure to update Travis config so that these are properly run on travis. Ivan just made some changes to peel out the filestore tests, so we need to update that.

**Comment by neilalexander** [comment]
Good point, I added a `bool` to `testAllStoreAllPermutations` to control whether or not to test all of the various compression and encryption options. When `false`, it now just tests the two stores:
```
=== RUN   TestStoreMsgLoadNextMsgMulti
=== RUN   TestStoreMsgLoadNextMsgMulti/Memory
=== RUN   TestStoreMsgLoadNextMsgMulti/File
--- PASS: TestStoreMsgLoadNextMsgMulti (0.01s)
    --- PASS: TestStoreMsgLoadNextMsgMulti/Memory (0.00s)
    --- PASS: TestStoreMsgLoadNextMsgMulti/File (0.01s)
PASS
ok      github.com/nats-io/nats-server/v2/server
```

I already copied in the same build tags that Ivan added to `filestore_test.go` last week so that should be fine.

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by kozlovic** [comment]
@neilalexander But you then need to add a `go test -v -race -run=TestStore ...` to the runTestsOnTravis.sh script (and GitHub action yaml file for good measure) because otherwise they will not be running. You can see that this new test did not run in any of the Travis runs.

**Comment by derekcollison** [comment]
Thanks @kozlovic, that was what I was worried about.

**Pull request merged**
