### PR TITLE
Consumer Updates.

### PR DESCRIPTION
**Pull request by derekcollison**
Make sure to not process next message (batch) requests inline if non client connection.
Added an index to the redeliver queue for large rdq scenarios.
Cleanup service exports and imports for JetStream.

/cc @nats-io/core

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM... still feel uncomfortable with the individual go routines.

**Comment by derekcollison** [comment]
Noted, but after review I did not feel Go routine with channels per account actually buys us anything and actually could provide undesirable behavior.

**Comment by derekcollison** [comment]
One last check on last CL that will error back to a pull request on push based consumer.

**Comment by ripienaar** [comment]
LGTM, I tested a few things manually like offline nodes

**Review by kozlovic — APPROVED** [review]
LGTM (you have a conflict to resolve: server/jetstream_cluster_test.go)

**Pull request merged**
