### PR TITLE
gnatsd: -health and -rank options

### LINKED ISSUE #433: cluster health monitoring - uses for system internal/read-only topics
To consolidate discussion on slack about using a system-internal topic to have servers provide health and cluster group membership information:

As a nats system operator, when gnatsd-cluster membership changes, I want:

(a) nats-top to be monitoring the correct set of all servers; (see also https://github.com/nats-io/nats-top/issues/31)

(b) to receive an event published on nats that gets translated into a pager duty call so I know what box to go reboot/reclone; 

(c) to allow the remaining set of servers’ clients to decide upon a new master to be the one writing.

Moreover, as a nats operator, when I run nats-top, for efficiency and ease of configuration:

(d) I don’t want to have to setup TLS. I want to avoid TLS between nats-top and my local gnatsd, and I want to avoid TLS between nats-top and any other remote gnatsd server.

Slack participants pointed out prior art in https://github.com/nats-io/gnatsd/pull/230, which is similar but we're talking here about monitoring gnatsd-to-gnatsd (intra-cluster) connections rather than client connections.

With help from the Slack discussions, I'm trying to work up pull-request that will address these. My plan is start with #230 and adjust as needed.

### PR DESCRIPTION
**Pull request by glycerine**
This is about half done. There's a bunch of polish (especially
around all the verbose and ugly logging the election
produces) and some tests are still left to do.

Still, one can see the basic architecture. And its that basic integration
architecture/approach that I wanted to get feedback on early. In
particular and specifically, if someone would vet the additions to server.go,
that's the integration point and the most likely place where I've
missed something important.

TODO:
[ ] get ServerRank actually configured, and see if ServerLocation() can be eliminated or finished out.
[ ] write up the leader election algorithm used here. It is ultra simple but still needs documenting.
[ ] write tests for the election
[ ] finish getting the health info nats-top is used to into a regular nats-topic
[ ] hook up that output to nats-top

eventual commit message, proposed:

Cluster health monitoring and
leader election and priority
assignment are made available
with the -health and -rank
flags to gnatsd.

The InternalClient interface offers
plugin capability for running
internal clients.

Allows nats-top to monitor the health
of the whole cluster.

Fixes #433 and https://github.com/nats-io/nats-top/issues/31

### CODE REVIEW

**Comment by glycerine** [comment]
NB, The CI checks will fail because the corresponding glycerine/go-nats `minhealth` branch is used (https://github.com/glycerine/go-nats/tree/minhealth if you want to pull them both to manually build). I'll polish the go-nats additions, which are small, and do a separate PR for them so that CI is useful here again.

**Comment by glycerine** [comment]
the PR for go-nats that will let you manually build this: https://github.com/nats-io/go-nats/pull/265 

status update:
[x] get ServerRank actually configured
[x] write up the leader election algorithm used here. It is ultra simple but still needs documenting.
[ ] write tests for the election. Still in progress.
[ ] finish getting the health info nats-top is used to into a regular nats-topic
[ ] hook up that output to nats-top

**Comment by glycerine** [comment]
The dependency, https://github.com/nats-io/go-nats/pull/265, is ready for review; then travis can work on this PR again.

**Comment by glycerine** [comment]
Status update: this is in good shape now. It doesn't have the nats-top part done yet, but election and heath monitoring agent are tested and polished.

**Comment by derekcollison** [comment]
Closing this due to age.

**Comment by varunpalekar** [comment]
We need this feature of health check

**Comment by derekcollison** [comment]
Help me understand what you are trying to do and what problem this is solving?

**Comment by varunpalekar** [comment]
Sorry, it gets lost in my todos. That time I was testing nats-server helm chart for deployment on kubernetes without using nats operators.
So facing some issue with healthcheck.

**Pull request closed without merging**
