### PR TITLE
Test-data certs reissuance (SHA1 -> SHA256)

### LINKED ISSUE #3298: Update TLS Certificates
Since Go 1.18, certificates with sha1WithRSAEncryption algorithm are not longer accepted, unless one export the `GODEBUG="x509sha1=1` environment variable.

It seem like we would need to update the following certificates:
```
test/configs/certs/client-cert.pem
test/configs/certs/client-id-auth-cert.pem
test/configs/certs/server-cert.pem
test/configs/certs/server-iponly.pem
test/configs/certs/server-noip.pem
test/configs/certs/srva-cert.pem
test/configs/certs/srvb-cert.pem
```

### PR DESCRIPTION
**Pull request by philpennock**
- [x] Testdata recreation script added
 - [x] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
   - No, there's a "code" change" and a "generated data" change and I've kept them separate
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

Resolves #3298 

### Changes proposed in this pull request:

 - Add a script to regenerate the X509 certs which were still using SHA1 as MD algorithm
 - Regenerate those certs
 
/cc @nats-io/core

### CODE REVIEW

**Comment by philpennock** [comment]
There was a typo such that `server-iponly.pem` did not correspond to `server-key-iponly.pem`; fixed, squashed appropriately.

**Comment by philpennock** [comment]
Branch tests failed, PR test failed on something unrelated which looks like a flapper (jetstream expected counts).  Restarted that test.

**Comment by philpennock** [comment]
Tests passing, marked ready-for-review.  Have fun.

**Comment by kozlovic** [comment]
@philpennock @derekcollison I just did and pushed a new commit. Let's see if that still work :-)

**Review by kozlovic — APPROVED** [review]
LGTM. Tests have passed without the GODEBUG env variable!

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
@kozlovic feel free to merge.

**Pull request merged**
