### PR TITLE
audit api events

### PR DESCRIPTION
**Pull request by ripienaar**
this is no doubt far from perfect, or maybe just completely not
right even, but was playing around with this so figure I'll stick
it up

### CODE REVIEW

**Comment by ripienaar** [comment]
```json
{
  "schema": "io.nats.jetstream.advisory.v1.api_audit",
  "id": "vxmyHUWVolRfWUHjzWlCPh",
  "timestamp": 1579514845884692000,
  "account": "$G",
  "user": "User \"N/A\"",
  "client": "127.0.0.1:57563 - cid:6",
  "request": "{\"name\":\"test2\",\"subjects\":[\"test2\"],\"retention\":\"limits\",\"max_consumers\":-1,\"max_msgs\":-1,\"max_bytes\":-1,\"max_age\":0,\"max_msg_size\":-1,\"storage\":\"file\",\"num_replicas\":0}",
  "subject": "$JS.STREAM.test2.CREATE"
}
```

**Comment by ripienaar** [comment]
suspect we'd need to specifically handle things like auth fails as additional events? there's no way of knowing from this if was allowed/denied/handled, so I suspect the final implementation will be a lot more verbose

**Comment by derekcollison** [comment]
I think from just looking at schema its pretty good. We need response for sure in there.

**Comment by derekcollison** [comment]
Client we should break out to uri or even host and separate port (which will be ephemeral anyway). Not sure client ID useful, could add it in as separate CID field.

**Comment by derekcollison** [comment]
Good stuff, thanks. Will take a look after morning meetings.

**Comment by ripienaar** [comment]
We can close this one yeah?

**Comment by derekcollison** [comment]
Yes I believe so.

**Pull request closed without merging**
