### PR TITLE
Cleaning up unused accounts

### PR DESCRIPTION
**Pull request by matthiashanel**
So far, having exports or js means cleanup is skipped

Signed-off-by: Matthias Hanel <mh@synadia.com>

These are the beginnings of account removal.
So far accounts with jetstream or exports are skipped.

If you approve of this one I'd look into that next. 
(suggestions on how to remove in the presence of jetstream are welcome)
For accounts with exports I'd check if the account can just be removed and importer set to incomplete.

### CODE REVIEW

**Comment by derekcollison** [comment]
How do you determine they should be cleaned up?

**Comment by kozlovic** [comment]
Could this wait post 2.2? I honestly don't know (and don't have the resource to check) if removing an account is going to cause problems (think gateways, soon mqtt, etc..).

**Comment by derekcollison** [comment]
I am feeling same tbh..

**Comment by matthiashanel** [comment]
@derekcollison @kozlovic sure post 2.2 is fine

The removal process (putting the account name into cleanupChan) is initiated when we remove the last client of an account.
In the go routine accountCleanup a lru list of these account names to check is maintained. 
Once the list size exceeds MaxUnusedAccounts we pick an account that was unused the longest.
We check if the initial conditions (account has no client) still holds.
If so, the account is removed and cleaned up once we exceed MaxUnusedAccounts. 
If not we wait for the next time a las client disconnects.

**Comment by matthiashanel** [comment]
As a reminder to myself. To get rid of accounts with exports remove the account and make the importing accounts appear as if they failed to download the exporting account. (put the discarded account into s.incompleteAccExporterMap.Store(i.Account, struct{}{}))

Consider pass through accounts where import => export

**Pull request closed without merging**
