### PR TITLE
Remove Roadmap

### PR DESCRIPTION
**Pull request by ColinSullivan1**
Remove the roadmap in lieu of the public roadmap on NATS site.

Signed-off-by: Colin Sullivan <colin@synadia.com>

/cc @nats-io/core

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]

**Comment by Jarema** [comment]
Wouldn't it be good to point to the Roadmap on NATS site in `Readme.md`?

**Comment by matthiashanel** [comment]
> Wouldn't it be good to point to the Roadmap on NATS site in `Readme.md`?

@ColinSullivan1 I second that. Would we have a link at this time?

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ColinSullivan1** [comment]
We can - I can do that in this PR, or separately.  Ivan, wdyt?

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ColinSullivan1** [comment]
Added!  Thanks for the suggestions all.

**Pull request merged**
