### PR TITLE
ensure deliver policy can be unmarshalled

### PR DESCRIPTION
**Pull request by ripienaar**
Signed-off-by: R.I.Pienaar <rip@devco.net>

### CODE REVIEW

**Comment by ripienaar** [comment]
hate++ this pattern of code :)

**Comment by ripienaar** [comment]
it's good the way it is, more a general Go gripe - however it would help to put all this related code in one place (made the same mistake on the weekend copy/pasting into jsm)

**Comment by derekcollison** [comment]
Agree, but as you point out will only help Go. However as we get settled should do that formalized API thing.

**Comment by ripienaar** [comment]
I mean right now the marshal code is in store.go and the rest is in consumer.go - so its really easy to miss this.  All in one place is clearer

**Comment by derekcollison** [comment]
Gotcha.

**Pull request merged**
