### PR TITLE
add the nats utility into the server container

### PR DESCRIPTION
**Pull request by ripienaar**
- [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

### Changes proposed in this pull request:

@ColinSullivan1 suggested we might add the `nats` binary to the server container, so here it is.
Happy to defer till later

/cc @nats-io/core

### CODE REVIEW

**Comment by ripienaar** [comment]
> We should rename docker image, or pull GH repo and build in place. Starting to mix and match.

we could only pull and build in place once jetstream is in master, go mod will not do the right thing for building nats utility using `go get` and for nats-server build we'd have to switch branches etc.  Many pain points with JS not being in master.

**Comment by kozlovic** [comment]
Just wanted to add that this Dockerfile is not used when producing the docker image that one finds on https://hub.docker.com/_/nats. I believe that this alpine Docker may be used for nats-box or something else? @wallyqs would know better.

**Comment by wallyqs** [comment]
The result of this image is currently mostly used for beta builds of the nats-server that we eventually push to NGS for example (without waiting for the docker official image releases).  That list of images are here: https://hub.docker.com/r/synadia/nats-server/tags

**Comment by ripienaar** [comment]
Yes I knew about the official docket stuff. Wanted to get it into the non official stuff to test and see what issues we cause. Thanks both.

**Comment by derekcollison** [comment]
ok maybe ok then if @wallyqs signs off.

**Pull request closed without merging**
