### PR TITLE
added security for monitoring url with monitor token (optional)

### PR DESCRIPTION
**Pull request by shantanubansal**
- [ ] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [ ] Tests added
 - [ ] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [ ] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #

### Changes proposed in this pull request:

(IMP CHANGE TO SECURE MONITORING URL)

This will help secure nats monitoring url with the monitor token.
Now event the monitoring details won't be available if monitor_token or monitortoken is  configured in the config file.
this way we can secure the monitoring url plus if somebody don't want to secure it they dont have to add anything

If set they have to provide the token as a query param
eg:
<BaseUrl>/varz?token=<MONITOR_TOKEN>

 -
 -
 -

/cc @nats-io/core

### CODE REVIEW

**Comment by derekcollison** [comment]
I invited @kozlovic, @ripienaar and @wallyqs to take a look and comment.

**Comment by ripienaar** [comment]
I think this approach is fine in isolation, but please keep in mind we are a generic tool used in many many scenarios and circumstances and we simply would never be able to add enough control over this particular socket to make everyone happy.

Some wants a token, some want username/password (you wouldnt want to leak tokens in proxy logs?) some wants bearer tokens in headers, other wants client certificate validations, others want TLS, lets encrypt or private etcetc.  It's endless.

So I think rather than forever chasing our tail here we have to say NATS as a tool runs in a protected network and people have to expose the monitoring port to their monitoring systems using appropraite proxies, ingress, WAF or whatever they like.

So I agree with @derekcollison on this one for sure.

**Comment by kozlovic** [comment]
From a technical point of view, the PR has some issues that would need to be addressed. As you can see the code is generating panics. 
We would not functions that say if monitoring is secured out of the Options object. 
Also, if we were to go the direction of the token, would we want to even consider a misconfiguration if token is used but with http port (instead of https)?

**Comment by shantanubansal** [comment]
I will take care of all panics and proper error return.
I think we should allow HTTP with token as this can be used within a network too.

**Comment by kozlovic** [comment]
But you do understand that if token is sent in plain text, anybody can sniff the traffic and steal it. Point is that in this case I would not configure with token if not https.

It seems that as a group, we may not go this direction. We prefer now to use system messages since all the security is built-in in accounts, user auth, etc..

That being said:

> I will take care of all panics and proper error return.

And again, do not use IsMonitoringAllowed and IsSecureMonitoring from Options struct. Instead, the server's isMonitoringAllowed() should get the options using `s.getOpts()` and then you can access MonitorToken from the result. Otherwise, you are going to introduce races in case of configuration reload, etc..

**Pull request closed without merging**
