### PR TITLE
fix and improve unit test

### PR DESCRIPTION
**Pull request by matthiashanel**
reduce number of messages sent
try move+cancel for every server

Signed-off-by: Matthias Hanel <mh@synadia.com>

 - [ ] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [ ] Tests added
 - [ ] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [ ] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

Resolves #

### Changes proposed in this pull request:

 -
 -
 -

/cc @nats-io/core

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM. From 155 seconds down to 7 seconds or less, I'll take that ;-)

**Review by derekcollison — COMMENTED** [review]
I like it too, but reason it was large was it was not showing any issues with small number of messages. So the large number was to catch those scenarios.

**Comment by kozlovic** [comment]
@derekcollison I mentioned that if the big number was needed, then it should be moved to the "no race" tests, but @matthiashanel mentioned that he was able to get the desired condition with only 1000 messages.

**Comment by matthiashanel** [comment]
> I like it too, but reason it was large was it was not showing any issues with small number of messages. So the large number was to catch those scenarios.

The intent was to make sure move was in progress, but since this is timer based the large number was not really needed

**Pull request merged**
