### PR TITLE
Cherry picks for v2.10.21 RC1

### PR DESCRIPTION
**Pull request by wallyqs**
Includes:

- https://github.com/nats-io/nats-server/pull/5854/
- https://github.com/nats-io/nats-server/pull/5863/
- https://github.com/nats-io/nats-server/pull/5869
- https://github.com/nats-io/nats-server/pull/5886
- https://github.com/nats-io/nats-server/pull/5893
- https://github.com/nats-io/nats-server/pull/5896
- https://github.com/nats-io/nats-server/pull/5852
- https://github.com/nats-io/nats-server/pull/5781
- https://github.com/nats-io/nats-server/pull/5887

### CODE REVIEW

**Comment by derekcollison** [comment]
Should pull in updates to dependencies as well.

I can look at complete list of PRs since 2.10.20 later on..

**Comment by wallyqs** [comment]
Added the dependencies updates, some test fixes and this fix for stream create (https://github.com/nats-io/nats-server/pull/5854)

**Comment by derekcollison** [comment]
Any others we should pull in from your perspective?

**Comment by wallyqs** [comment]
There are some other PRs with testing updates that we could also include:
- https://github.com/nats-io/nats-server/pull/5852
- https://github.com/nats-io/nats-server/pull/5781
- https://github.com/nats-io/nats-server/pull/5862

Also need to bump the Go version to 1.22.7 for the release.

**Comment by derekcollison** [comment]
Up to you on test updates, not customer impacting but might make release easier to get through the builds.

+1 on bumping Go version. Any Alpine updates we need to consider?

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by wallyqs** [comment]
This one is ready, we are ok on alpine changes too.

**Pull request merged**
