### PR TITLE
Make sure to suppress dupes on JS deny all for system account

### LINKED ISSUE #2500: automatically inserted LN export/import deny rules for JetStream keep accumulating on LN reconnects
The user confirmed this is happening on reconnect and that the line below causes it
https://github.com/nats-io/nats-server/blob/874c79fe411f31291d7196b3ddd3500c8c82283b/server/leafnode.go#L1069

We need to make sure that these functions 
```go
s.addInJSDenyAll(remote)
s.addInJSDeny(remote)
s.addInJSDenyExport(remote)
acc.AddMapping(src, jsAllAPI)
```

Original user observation (presumably from our monitoring endpoints)
```json
         "deny": {
            "exports": [
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>"
            ],
            "imports": [
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>",
              "$JSC.>",
              "$NRG.>",
              "$JS.API.>"
            ]
```

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

Resolves #2500 

/cc @nats-io/core

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM, but note that you had some of this fix in a PR that is in draft status: https://github.com/nats-io/nats-server/pull/2411

**Review by matthiashanel — APPROVED** [review]
LGTM

**Comment by matthiashanel** [comment]
> LGTM, but note that you had some of this fix in a PR that is in draft status: #2411

**Comment by matthiashanel** [comment]
pressed wrong button

**Comment by derekcollison** [comment]
Once green will merge.

**Pull request merged**
