### PR TITLE
unify storeRawMsg for filestore and memstore

### PR DESCRIPTION
**Pull request by alexpantyukhin**
- [ ] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [ ] Tests added
 - [ ] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #

### Changes proposed in this pull request:

 - Unify storeRawMsg for filestore and memstore

/cc @nats-io/core

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
I'm not sure that is the good improvement, but it would be nice to consider and discuss.

**Review by derekcollison — COMMENTED** [review]
Prefer to leave the impls separate for the time being.

**Comment by alexpantyukhin** [comment]
@derekcollison I see. Yeah, I was wondering about unify these methods. In common these have the same logic, and unification could be good. But as far as it the same now it could change in future and need to split it again,
Should I close the PR?

**Comment by derekcollison** [comment]
Yes we may do this in the future but for now good to close.

**Pull request closed without merging**
