### PR TITLE
Allow for audit exception for `$JS.EVENT.>` and `$SYS.ACCOUNT.>` which may already exist.

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by neilalexander — APPROVED** [review]
LGTM

**Review by wallyqs — DISMISSED** [review]

**Comment by derekcollison** [comment]
Added in protection for ">" as well. Fixed tests, so should be green now.

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by wallyqs — APPROVED** [review]
LGTM

**Pull request merged**
