### PR TITLE
TLS testdata automation & reissuance

### PR DESCRIPTION
**Pull request by philpennock**
- TLS testdata: automate more cert issuance
- TLS testdata: invoked regenerate_rdns_svid.sh

/cc @nats-io/core

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
There is an issue parsing root cert..

**Review by derekcollison — APPROVED** [review]
LGTM

**Review by wallyqs — APPROVED** [review]
LGTM, thanks Phil!

**Pull request merged**
