### PR TITLE
Make ping/pong responses update last activity

### PR DESCRIPTION
**Pull request by wallyqs**
Changes ping/pong interval to also make updates to LastActivity to better reflect possible stale connections via monitoring.

### CODE REVIEW

**Review by derekcollison — COMMENTED** [review]
Not sure we want this, as discussed knowing a connection has been idle from an app perspective is quite helpful.

**Comment by wallyqs** [comment]
As different part of metadata from the ConnInfo to track the ping/pong activity (`last_ping_activity`) maybe? Something like: https://github.com/wallyqs/nats-server/commit/4915087f21f78a27012d77b60ebb8dfa7ae5fe2d

**Comment by derekcollison** [comment]
Possibly, but not sure if that info is useful in real world scenarios.. WDYT?

**Comment by wallyqs** [comment]
Good point, it would be rare to monitor a live stale connection error as it happens and this would be stored as part of the closed connections anyway. I will close this one for now.

**Pull request closed without merging**
