### PR TITLE
Fixed flapping test

### PR DESCRIPTION
**Pull request by kozlovic**
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Review by matthiashanel — APPROVED** [review]
LGTM

**Comment by kozlovic** [comment]
@matthiashanel Got a failure in one of the run regarding number of expected dirs not being correct. I am not fixing the issue per-se, but I pushed a new commit to replace the manual concatenation of the file name with filepath.Join(). Will have to keep an eye on that new failure condition...

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
