### PR TITLE
Change code coverage GHA workflow to use main

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Review by neilalexander — APPROVED** [review]
LGTM

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by bruth** [comment]
Can someone kick the flapper?

**Comment by kozlovic** [comment]
It was intentional that it referenced the `dev` branch, because `dev` was `main` + other stuff, so we wanted to have code coverage of `dev`. I am pretty sure that the failure is not related to that, but we will see.

**Comment by bruth** [comment]
Understood. It is suspicious to me as well since I don't understand why it would start failing after the merge. This may not be the fix, but overlooked in the dev &rarr; main merge nonetheless.

**Comment by kozlovic** [comment]
Changes were made in the `dev` branch, such as `checkout@v3` and some others, that were never tested since the code coverage was running from the `main` branch. Doing a `blame` shows 2/3 changes that may have contributed to the failure after being merged to main.

**Comment by derekcollison** [comment]
Should we merge or hold?

**Comment by neilalexander** [comment]
Suggest we merge, the `dev` branch is going away either way.

**Comment by bruth** [comment]
Shall we kick the flapper or merge since it succeeded for the PR? (I don't have permission to kick the flapper)

**Pull request merged**
