### PR TITLE
update readme to point to new CLI and updated guide

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Comment by derekcollison** [comment]
The other JSM checked in yes?

**Comment by ripienaar** [comment]
Yes, checked in, readme updated, uses go mod etc. 

I am iterating on it a bit but it’s in and ready

**Comment by derekcollison** [comment]
ok great will take a look Tied up today.

**Comment by ripienaar** [comment]
squashed and rebased onto latest jetstream

**Comment by ripienaar** [comment]
Would be nice

**Comment by derekcollison** [comment]
ok will look to merge in morning. I have the active fix but still want to tweak it a bit.

**Pull request merged**
