### PR TITLE
[FIXED] Panic on nil sysAcc

### PR DESCRIPTION
**Pull request by MauriceVanVeen**
Signed-off-by: Maurice van Veen <github@mauricevanveen.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

Ping me when off draft and I will merge.

**Review by neilalexander — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
This test is flapping all of the sudden. @MauriceVanVeen can you take a look?

`TestNoRaceJetStreamClusterGhostConsumers`

image

**Comment by MauriceVanVeen** [comment]
That test was already a flapper before, there are also other flappers, like `TestNoRaceJetStreamClusterCheckInterestStatePerformanceWQ`

```
=== RUN   TestNoRaceJetStreamClusterCheckInterestStatePerformanceWQ
    norace_test.go:11062: require true, but got false
--- FAIL: TestNoRaceJetStreamClusterCheckInterestStatePerformanceWQ (2.91s)
```

We need to take a look at them either way, but just wanted to say it's not because of this PR/change.

**Pull request merged**
