### PR TITLE
Adding check for to/prefix in wrong context

### PR DESCRIPTION
**Pull request by matthiashanel**
to is not applicable to streams
prefix is not applicable to services

Signed-off-by: Matthias Hanel <mh@synadia.com>

### CODE REVIEW

**Comment by derekcollison** [comment]
But they will be soon, so not sure we want to back them out yet. Will change over to to and from for both at some point. We can support it now with wildcards etc.

**Comment by kozlovic** [comment]
@matthiashanel Based on Derek's comment, sounds like we should close this PR, no?

**Comment by matthiashanel** [comment]
@kozlovic , @derekcollison 
> @matthiashanel Based on Derek's comment, sounds like we should close this PR, no?
Before closing I'll look up the new syntax.

**Comment by derekcollison** [comment]
Its not plumbed in yet. But the service rewrite now allows us to properly have to and from, or local and remote with wildcards. Can redo streams as well, but will need to keep backward compatibility with prefix.

**Comment by matthiashanel** [comment]
@derekcollison , so the new syntax is backwards compatible with to? And we would deprecate prefix?

**Comment by derekcollison** [comment]
Can't deprecate prefix, but would offer to for streams that did the right thing even with wildcards.

**Comment by matthiashanel** [comment]
@kozlovic @derekcollison , will close this one

**Pull request closed without merging**
