### PR TITLE
updated jsm utility with interactive prompts and more

### PR DESCRIPTION
**Pull request by ripienaar**
current jsm work, I think it's pretty good - though check what awful thing I did to the memstore pls

I have questions:

 * What is the `all` ack policy, I understand that is the one that if you ack message 100 then messages 1-99 is also acked?
 * is delete message already implemented?
 * I think we need a better term to describe `ack floor` :)

### CODE REVIEW

**Comment by ripienaar** [comment]
The CLI tests I added will make CI runs a fair bit slower but I think we need them, not sure how to speed it up, maybe run `go build` first then just ./jsm, cos this go run hack is... a hack.

**Comment by derekcollison** [comment]
Go ahead and squash this down, then let's figure out between you and I and @kozlovic whether or not we make it its own repo.

**Comment by ripienaar** [comment]
@derekcollison ok, I made tests pass and all. 

My pref would be for a new repo for this.

**Comment by derekcollison** [comment]
My bet is that @kozlovic will agree. Let's do that. Call it jetstream and have jsm directory and we can dupe README from jetstream dir (with updates) for now.

**Comment by ripienaar** [comment]
https://github.com/nats-io/jetstream and pr https://github.com/nats-io/nats-server/pull/1221

The jetstream repo vendors nats-server with the above PR applied, I'll close this PR then and we pick it up in those.

**Comment by derekcollison** [comment]
Might be overkill. Maybe just use modules and pull in that way, or we can duplicate the subjects and structures.

**Comment by ripienaar** [comment]
now that the PR is merged and I can reference it in a module, 100% thats what I am going to do :)

**Pull request closed without merging**
