### PR TITLE
Avoid race condition

### PR DESCRIPTION
**Pull request by derekcollison**
Have seen this one a few times trigger race detector.

Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

**Review by ripienaar — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
I have a deadlock, will check this out in a few. We had this before, its coming back to me now ;)

**Comment by derekcollison** [comment]
I kept second CL separate for now to see what was deadlocking that code.

**Review by ripienaar — APPROVED** [review]
LGTN

**Pull request merged**
