### PR TITLE
Add a pre-commit hook for the repo

### PR DESCRIPTION
**Pull request by philpennock**
This is Derek's list of desired checks, but wrapped up with update policy checks etc to be more appropriate for a git-hook which is used in an repository with commits from various places.

Signed-off-by: Phil Pennock <pdp@nats.io>

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by neilalexander** [comment]
Pretty sure all of these are already covered by our `golangci-lint` config, which should integrate with the Go language server in compatible editors and be runnable by hand with `golangci-lint run` if not. The CI pipeline also does this in the compile & test step. For consistency we probably should be using that.

**Comment by kozlovic** [comment]
I would agree with @neilalexander in that we are already running checks in CI and one should not make direct commits to the `main` branch anyway, so errors should be caught by the developer when submitting their PR.

**Comment by derekcollison** [comment]
Let's rework, but no rush.

**Comment by philpennock** [comment]
I think there's no need to keep this PR around.  This one was just to add the checks as requested, but done in a way safe for use with a repo with various committers.  If the goal is to switch to more standard checks, then that should be its own PR.

**Pull request closed without merging**
