### PR TITLE
Merge branch 'main' into dev

### PR DESCRIPTION
**Pull request by Jarema**
cc @jnmoyne 

 Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Comment by derekcollison** [comment]
You do a `git merge main --no-ff`?

**Review by derekcollison — APPROVED** [review]
LGTM if tests are green, have @jnmoyne take a peek as well.

**Comment by Jarema** [comment]
@derekcollison yes, done on temporary branch to allow reviewing the changes (especially @jnmoyne).
Next,  use `rebase and merge` to not generate another merge commit (Merge temp-dev into dev). That should be effectively the same history as with `git merge main --no-ff`  directly on `dev`, but allowing for reviews.

**Review by jnmoyne — COMMENTED** [review]
LGTM

**Review by jnmoyne — APPROVED** [review]
LGTM

**Pull request merged**
