### PR TITLE
Add support for custom dialers and listeners

### LINKED ISSUE #668: Add CustomListener to Opts
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
## Feature Requests
Allow passing an initialized `net.Listner` so when the Server starts, it does not bind a new connection. This gives more control over the socket.

#### Use Case:
This would allow more advanced custom handshakes for TCP connections. Paired with CustomDialer in `go-nats` it would allow you to easily setup custom connection initialization. This is useful for more advanced security protocols or if you want to run multiple servers on one connection.
 
#### Proposed Change:
* Add `CustomListener` option to Opts. 
* In `AcceptLoop` use `Opts.CustomListner` if available else fallback to `net.Listen`.
 
#### Who Benefits From The Change(s)?
People  who want more control over how connections are handled.

### PR DESCRIPTION
**Pull request by hansonkd**
- [x] Resolves #668 
 - [ ] Documentation added (if applicable)
 - [ ] Tests added
 - [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #668

### Changes proposed in this pull request:

 - Add `ClientListener` `RouteListener` and `RouteDialer` to Server Options

This has allowed me to implement multiplexing multiple servers off of one socket. This can also let you implement a websocket server embedded directly in the same process the nats server (Because gnatsd will accept arbitrary `net.Conn`).

Overall this gives much more flexibility in managing sockets and connections with very little restructuring of the server.

/cc @nats-io/core

### CODE REVIEW

**Comment by kozlovic** [comment]
@hansonkd Thanks, we will get back to you on this.

**Comment by 0x1a8510f2** [comment]
I'm starting to lose faith in @kozlovic getting back to this :P. Any chance of this PR being reopened?

I'd love to see this merged as it's a tiny change and would be extremely helpful for my usecase and, no doubt, others. My usecase involves having NATS listen on an overlay network. The binary will have an embedded network stack and with this change I can easily point NATS server at it.

FWIW it looks like this functionality is pretty standard across the Go ecosystem, including in the standard library HTTP server (`.Serve()` on a HTTP server takes a `net.Listener` which covers this), so I was surprised to see a lack of this here.

I couldn't easily replicate this functionality with `InProcessConn()` because it returns a conn as opposed to accepting one.

**Comment by 0x1a8510f2** [comment]
I've looked a little deeper and it appears that the needed changes are actually a little more complex after 5 years of work on the codebase than what is in this PR. Who could have expected that!? Anyway, I'll either make those changes and open a PR (hoping it gets accepted) or try to figure something out with `InProcessConn`, whichever is the path of least resistance :D

**Comment by derekcollison** [comment]
I would recommend InProcessConn().

**Pull request closed without merging**
