### PR TITLE
MQTT: Cleanup code regarding retain flag and add test

### PR DESCRIPTION
**Pull request by kozlovic**
As per specification MQTT-3.3.1-8, we are now setting the RETAIN flag when delivering to new subscriptions and clear the flag in all other conditions.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by derekcollison** [comment]
This only for dev or should be for main too?

**Comment by kozlovic** [comment]
@derekcollison There have been "many" other fixes in Lev's PR that was against dev branch that we felt that this fix is ok to be in dev only. That being said, I can make it against "main" branch but there would be conflict merging into "dev" due to recent changes.

**Comment by derekcollison** [comment]
If applicable to main yes let's do that..

**Comment by kozlovic** [comment]
> If applicable to main yes let's do that..

Ok will do so in a bit.

**Comment by kozlovic** [comment]
@derekcollison @levb After further review, there was no bad behavior in that the retain flag was cleared (as expected) when processing a retained message, which means that the code in the "QoS0" callback that used the retain flag value to serialize the message to an existing subscription would have always be "false" (as it should). For the "QoS1" callback, the retain boolean was declared but never set, so again the end-result was correct behavior.

I have changed the title of this PR to make it clear that this is more of a code cleanup, no defect is being fixed. I therefore propose to leave this against "dev" and not have a PR for "main" since there was no defect per-se.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
