### PR TITLE
Cherry-picks for 2.10.17-RC.5

### PR DESCRIPTION
**Pull request by neilalexander**
Includes the following:

* #5552 
* #5557
* #5556
* #5558

Signed-off-by: Neil Twigg <neil@nats.io>

### CODE REVIEW

**Comment by neilalexander** [comment]
@aricart 
```
server/auth_callout_test.go:1989:19: undefined: ServerAPIClaimUpdateResponse
```
Is #5555 supposed to be for 2.10.17?

**Comment by aricart** [comment]
@neilalexander yes I think Derek wanted to include it - let me see if I can change the test to not rely on that type

**Comment by aricart** [comment]
@neilalexander added PR to fix test https://github.com/nats-io/nats-server/pull/5561

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by neilalexander** [comment]
Excluded #5555 for now as will get the test sorted out for the next RC but we have NGS users blocked on the advisory streams.

**Pull request merged**
