### PR TITLE
Nightly: set Go version to 1.17 and use latest goreleaser

### PR DESCRIPTION
**Pull request by kozlovic**
[ci skip]

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
I have verified in running the Nightly from this branch that it now uses Go 1.17:
```
Digest: sha256:8af6d1d79ebdc5e78426a38bacafce18cf5f2100733120bb197731e8ad77e2ab
Status: Downloaded newer image for synadia/nats-server:nightly
[1] 2022/01/26 22:33:07.476297 [INF] Starting nats-server
[1] 2022/01/26 22:33:07.476350 [INF]   Version:  2.7.1
[1] 2022/01/26 22:33:07.476353 [INF]   Git:      [609a9ba2]
[1] 2022/01/26 22:33:07.476354 [DBG]   Go build: go1.17.6
[1] 2022/01/26 22:33:07.476358 [INF]   Name:     NBIAUX6WE2Y7QFCBJ4NXEOHLPJ44FQI4MPY6QAPSFIOQC77ONG2CYJ5A
[1] 2022/01/26 22:33:07.476363 [INF]   ID:       NBIAUX6WE2Y7QFCBJ4NXEOHLPJ44FQI4MPY6QAPSFIOQC77ONG2CYJ5A
[1] 2022/01/26 22:33:07.476419 [DBG] Created system account: "$SYS"
[1] 2022/01/26 22:33:07.476910 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2022/01/26 22:33:07.476954 [DBG] Get non local IPs for "0.0.0.0"
[1] 2022/01/26 22:33:07.477292 [DBG]   ip=172.17.0.2
[1] 2022/01/26 22:33:07.477333 [INF] Server is ready
```
After this is merged, I will trigger the build again.

**Review by ripienaar — APPROVED** [review]
I do recall a reason for pinning to that goreleaser but let’s see I guess. Don’t remember details.

**Comment by kozlovic** [comment]
@ripienaar It was because that was the last release to support vendor. I did release NATS Server with the latest goreleaser and it works. Also, I tried the nightly from this branch, and as you can see it works.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
