### PR TITLE
JetStream fixes for InterestPolicy retention

### PR DESCRIPTION
**Pull request by derekcollison**
This fixes both #1580 and https://github.com/nats-io/jetstream/issues/314

/cc @nats-io/core

### CODE REVIEW

**Comment by ripienaar** [comment]
Maybe not a direct result of this PR but this is a bit weird,

```json
  "state": {
    "messages": 0,
    "bytes": 0,
    "first_seq": 3,
    "first_ts": "1970-01-01T00:00:00Z",
    "last_seq": 2,
    "last_ts": "2020-09-03T11:57:53.7182588Z",
    "consumer_count": 0
  }
```

we have 3 messages (now deleted) and `first_ts` is 1970, I get why this is but it seems weird while last_ts is the last received message.  I know we spoke about these recently too, hard to know what the right behaviour is here

Otherwise this PR works for me

**Review by kozlovic — APPROVED** [review]
LGTM and verified that it would resolve issue that I saw.

**Comment by kozlovic** [comment]
@derekcollison Unrelated to this PR obviously, but following flapper:
```
=== RUN   TestLeafNodeDaisyChain
    leafnode_test.go:3330: Expected a response
--- FAIL: TestLeafNodeDaisyChain (1.10s)
```
I believe could be resolved with adding:
```
checkSubInterest(t, s3, "$G", "ngs.usage", time.Second)
```
to `test/leafnode_test.go:3323`.

**Comment by derekcollison** [comment]
Will fix leafnode test.

**Comment by derekcollison** [comment]
R.I. regarding last ts, understand but I feel we really need state to hold last message received at all times, especially when the stream has been emptied vie expiration or purge.

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ripienaar** [comment]
I agree on the last, but here first behaviour seems at odds then

**Comment by ripienaar** [comment]
I also just noticed that if I add a consumer messages are kept - but if I delete the only consumer messages remain

```json
{
  "config": {
    "name": "INTEREST",
    "subjects": [
      "js.in.interest"
    ],
    "retention": "interest",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000
  },
  "state": {
    "messages": 1,
    "bytes": 45,
    "first_seq": 2,
    "first_ts": "2020-09-03T14:57:14.966587902Z",
    "last_seq": 2,
    "last_ts": "2020-09-03T14:57:14.966587902Z",
    "consumer_count": 0
  }
```

**Comment by derekcollison** [comment]
ok let me look into that real quick and add a test for that. Removing the consumer removes interest so should have the messages removed.

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by ripienaar** [comment]
LGTM but I can only properly test tomorrow

**Pull request merged**
