### PR TITLE
Fix bug in needAck

### PR DESCRIPTION
**Pull request by Jarema**
needAck has reverse logic for checking single subject-single filter
    scenario.

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM!

**Comment by derekcollison** [comment]
Make not a draft and we can merge it in. 

Do you have a test for it?

**Comment by derekcollison** [comment]
Should we get a test in here too?

**Comment by Jarema** [comment]
Would be good. Working on it.

**Comment by Jarema** [comment]
Tests added.

**Review by derekcollison — APPROVED** [review]

**Pull request merged**
