### PR TITLE
Fixed a route pooling flapper

### PR DESCRIPTION
**Pull request by kozlovic**
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM - Thanks!

**Comment by kozlovic** [comment]
@wallyqs Here is my attempt at fixing the flapper you have mentioned to me. I increased the number of attempts we let the test settle but use routeConnectDelay, which in test is 15ms instead of the constant that is 1sec. I did not see it flap with these changes on my machine.

**Review by wallyqs — APPROVED** [review]
LGTM, thanks Ivan!!

**Comment by kozlovic** [comment]
@derekcollison @wallyqs I have seen TestRoutePoolConnectRace fail on Travis (not on my machine so far). Having a look on that one too. Could we keep this PR opened a bit to see if I have an update?

**Comment by kozlovic** [comment]
@derekcollison @wallyqs I modified the test that was failing. The number of duplicate logs was too small given the size of the cluster and pool size. I have verified that if I make the code "fail" (by not preventing the reconnect when detected as duplicate), the test will fail even with the new limit of 20. With correct code, I have seen in my tests that the number of "duplicate" log messages could go to 16 or so in some cases but will then stop. So the new limit of 20 seem ok but could be increased easily since it would not prevent detecting the bug (of constant reconnect).

**Review by wallyqs — APPROVED** [review]
LGMT, thanks!

**Pull request merged**
