### PR TITLE
Add config line allow_authentication_failure

### PR DESCRIPTION
**Pull request by MartinLeedotOrg**
- [ ] Documentation added (if applicable)
 - [x] Tests added
 - [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)
### Changes proposed in this pull request:

 - Add config line allow_authentication_failure
   - This is useful in deploying NATS 2.0 and slowly rolling out JWT authentication across all clients

/cc @nats-io/core

### CODE REVIEW

**Comment by derekcollison** [comment]
Can you give some more detail on the issue that you are trying to solve with this change? Thanks!

**Comment by MartinLeedotOrg** [comment]
The concept is that I would like to slowly introduce the new JWT authentication (https://nats-io.github.io/docs/nats_tools/nsc/nsc.html).

I would like to - for a couple of weeks - give developers a chance to get JWT authentication in to their application, while monitoring the logs to make sure some forgotten service hasn't slipped by.

**Comment by derekcollison** [comment]
This feels like a slippery slope security wise. We have the ability to lock down servers with operator public keys to force authentication even in the face of gaining access to the configuration file. This option would allow anyone with access to the config file to turn that authentication off.

I do understand what you are trying to achieve during this transition period however. But just so we are on the same page, you want applications with no auth (or non operator mode / JWT auth) to be allowed to access the system for a period of time without proper credentials, correct?

Do you have an auth scheme in place now? Does your system take advantage of multiple accounts or simple one at the moment?

**Comment by MartinLeedotOrg** [comment]
We're going to do this internally with some fancy clustering after a discussion with @derekcollison!

Thanks for the chat.

**Comment by derekcollison** [comment]
Let us know if we can help with anything additionally.

**Pull request closed without merging**
