### PR TITLE
[FEAT] enable scoped users to have templates that are not limited to a subject token

### PR DESCRIPTION
**Pull request by aricart**
Relaxed template logic to allow a template in a scoped user to be in line with the subject, enabling uses like `KV_{{tag(foo)}}`. This allows more flexibility for some arcane cases even if the tag requirement is that it will still be lower-cased.

Signed-off-by: Alberto Ricart <alberto@synadia.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by derekcollison** [comment]
Need to fix this..

image

**Comment by ripienaar** [comment]
nice, I'd be interested in exporting `processUserPermissionsTemplate` to provide a UI in `nats auth` that can show ACLs expanded during JWT info expanded just as the server would

**Comment by aricart** [comment]
> nice, I'd be interested in exporting `processUserPermissionsTemplate` to provide a UI in `nats auth` that can show ACLs expanded during JWT info expanded just as the server would

I got that and better: https://github.com/aricart/aclgenerator

**Pull request merged**
