### PR TITLE
Fix last per subject with multiple filters validation check

### LINKED ISSUE #4707: Different behavior between single node and clustered nats-servers regarding 'DeliverLastPerSubjectPolicy' with multiple subjects.
### Observed behavior

We have go code that runs an ordered consumer with two subjects and the 'DeliverLastPerSubjectPolicy'. It works great using a nats-server 2.10.3 as single node. But if we use the same code on the three nodes cluster, we get a strange error.

I checked out 'nats.go' and added a line to debug what is sent to nats-server. See image for reference:

image

This is the local server, single-server with no auth setup:

```
"$JS.API.CONSUMER.CREATE.kcl-orderlist.faQrdj1mbBnQdTMzO7DpLJ_1" / {"stream_name":"kcl-orderlist","config":{"name":"faQrdj1mbBnQdTMzO7DpLJ_1","deliver_policy":"last_per_subject","ack_policy":"none","replay_policy":"instant","inactive_threshold":300000000000,"num_replicas":1,"mem_storage":true,"filter_subjects":["kcl.v1.orderlist.*.*.*.*.data","kcl.v1.orderlist.*.*.info"]},"action":""} / (*jetstream.APIError)(nil)
```

This is the same code against our 3 node cluster running with an admin user (full access) on the:

```
"$JS.API.CONSUMER.CREATE.kcl-orderlist.b0bjYmCvgD8ZONdSKx3CuF_1" / {"stream_name":"kcl-orderlist","config":{"name":"b0bjYmCvgD8ZONdSKx3CuF_1","deliver_policy":"last_per_subject","ack_policy":"none","replay_policy":"instant","inactive_threshold":300000000000,"num_replicas":1,"mem_storage":true,"filter_subjects":["kcl.v1.orderlist.*.*.*.*.data","kcl.v1.orderlist.*.*.info"]},"action":""} / &jetstream.APIError{Code:400, ErrorCode:0x276e, Description:"consumer delivery policy is deliver last per subject, but FilterSubject is not set"}
```

### Expected behavior

Considering, that both servers are the same version (2.10.3) and everything else is working fine between the test and the staging system, I expected to have the same behavior.

Especially getting the error that the subjects are missing, while they are clearly in the JSON that is getting sent to the server makes me unhappy.

Here are the binary messages as another reference:

image

image

### Server and client version

Both nats-server versions are 2.10.3, but I also tried 2.10.1 and current main on the cluster.

The data (stream) in that account on the cluster should be identical with the test system. We delete the stream and recreate all the data beforehand.

### Host environment

We develop the code with go using WASM target, that is why I dug into the raw messages to avoid problems because of that fact.

The cluster is a three node cluster running on Debian Linux, with the nats-server compiled using go1.21.1 on that same machine, but I also downloaded the official release v2.10.3 Linux amd64 binary and used that instead.

### Steps to reproduce

Hard to tell. I would be grateful for ideas on what could be the culprit and how to test what may be the problem here. A wild guess of mine would be, that the storage on the cluster is not created new as the test system and was created some month ago.

When I change the subjects to just one of both, there is no error. When I use something like `kcl.v1.orderlist.>` there is no error and the app works (kinda, because it then gets some other messages that are unexpected). We could rearrange the subjects to work around this problem, but I wonder what is going on, why is it different, and how can this error happen in the first place?

### PR DESCRIPTION
**Pull request by Jarema**
Fixes #4707 

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Review by neilalexander — APPROVED** [review]
LGTM

**Review by neilalexander — APPROVED** [review]
Test looks good, thanks!

**Review by derekcollison — COMMENTED** [review]
LGTM

**Comment by oderwat** [comment]
Is there an ETA for the fix going to a release? We are waiting on it to remove the workarounds for production servers.

**Comment by derekcollison** [comment]
We are trying for this week for both 2.10.5 and 2.9.24.

**Pull request merged**
