### PR TITLE
[FIXED] Make access to mb's first and last sequence to consistently use atomics.

### PR DESCRIPTION
**Pull request by derekcollison**
Fixes data races.

Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Review by neilalexander — COMMENTED** [review]
In principle LGTM, but wonder if changing `first.seq` and `last.seq` to an `atomic.Uint64` type might be less error-prone than potentially forgetting `atomic.LoadUint64`/`atomic.StoreUint64` somewhere in the future and may also avoid any potential alignment issues?

**Comment by derekcollison** [comment]
Might be, could not remember when they introduced those but looking now is G0 1.19, so we should be good if we want to switch. Eventually I want the top level block selection to not need atomics or locks, but more for 2.11.

What alignment issues to you forsee?

**Comment by derekcollison** [comment]
I think we are ok alignment wise, but understand what you are saying.

I think for now will leave but agree if we keep this direction we should consider. But I think there is a better way for the upper layer indexing and block selection.

**Review by neilalexander — APPROVED** [review]
Yep agreed, LGTM!

**Review by wallyqs — APPROVED** [review]
LGTM

**Pull request merged**
