### PR TITLE
Default to replicas == 1 in tiered jetStream setup

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

/cc @nats-io/core

### CODE REVIEW

**Comment by ripienaar** [comment]
I think we tried this before and it was fraught with issues - if I recall correctly we had issues with defaults and comparibility of streams once created and loaded from disk or something, meaning clients would all fail.  Do you remember @derekcollison ?

**Comment by Jarema** [comment]
@ripienaar Yeah, got into bunch of weird issues when moving validation and estabilshing sane defaults before checking for limits, which was surprising, considering this looked like a low hanging fruit to be done on coffee break :).

Went with dirty approach with just setting replicas to 1 when tierName is derived from pre-validated (in single-server mode) Stream Config.
Does not look clean, but should not break anything at least.

**Comment by Jarema** [comment]
was hoping for an easy and clean fix for #3748 , but ended up doing exactly what the issue asks for.
Not clean, but without lots of hard to predict side effects.

**Comment by derekcollison** [comment]
@ripienaar I think we did but they were resolved a while back IIRC.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
